package com.paze.checkout.domain;

public enum ActionType {
    VERIFY_OTP,
    DEVICE_VERIFY,
    SELECT_CARD,
    VERIFY_CVV,
    CHANGE_CARD,
    SELECT_SHIPPING,
    PASSKEY_REGISTER_BEGIN,
    PASSKEY_REGISTER_FINISH,
    PASSKEY_REGISTER_SKIP,
    PASSKEY_AUTH_BEGIN,
    PASSKEY_AUTH_FINISH,
    PASSKEY_AUTH_CANCEL
}
